dist: trusty
language: php

env:
  - CODECOV_TOKEN="3d1735ac-5e08-4abc-986d-c88adaf77154"

php:
  - 5.6

before_install:
  - composer install
  - cp config/autoload/doctrine.sqlite.local.php.dist config/autoload/doctrine.local.php
  - vendor/bin/doctrine-module orm:schema-tool:create
  - composer fixtures-load

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry vendor/bin/php-coveralls
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
