dist: trusty
language: php

php:
  - 5.6

before_install:
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry vendor/bin/php-coveralls

notifications:
  email: false
