<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Feltöltés ideje</th>
            <th scope="col">Feltöltő</th>
            <th scope="col">Eredeti fájlnév</th>
            <th scope="col">Verzió</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($files as $file): ?>
            <tr>
                <th scope="row"><?= ++$i ?></th>
                <td><?= $file->getUploadedAt()->format('Y-m-d H:i:s') ?></td>
                <td><?= $file->getUploadedBy()->getFullName() ?></td>
                <td><a href="<?= $this->basePath('file/download/'.$file->getId()) ?>"><?= $file->getOriginalName() ?></a></td>
                <td><?= $file->getVersion() ?>.0</td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
