<?php

/*
 * Copyright (c) 2018 Puskás Zsolt <errotan@gmail.com>
 * Licensed under the MIT license.
 */

namespace Application\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllAsTree()
    {
        $categories = $this->findBy([], ['parentId' => 'ASC', 'name' => 'ASC']);
        $childs = [];

        foreach ($categories as $category) {
            $childs[$category->getParentId()][] = $category;
        }

        foreach ($categories as $category) {
            if (isset($childs[$category->getId()])) {
                $category->childs = $childs[$category->getId()];
            }
        }

        return $childs[0];
    }
}
