<h5><?= $user->getFullName() ?> felhasználó jogosultságai</h5>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Kategória</th>
            <th scope="col">Feltölthet</th>
            <th scope="col">Letölthet</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($acls as $acl): ?>
            <tr>
                <th scope="row"><?= ++$i ?></th>
                <td><?= $acl->getCategory() ? $acl->getCategory()->getName() : '-minden-' ?></td>
                <td><?= $acl->getCanUpload() ? 'Igen' : 'Nem' ?></td>
                <td><?= $acl->getCanDownload() ? 'Igen' : 'Nem' ?></td>
                <td>
                    <i class="fas fa-sm fa-edit pointer js-modal-load" data-url="<?= $this->basePath('acl/edit/'.$acl->getId()) ?>" data-toggle="modal" data-target="#modal" title="Jogosultság szerkesztés"></i>
                    <i class="fas fa-sm fa-trash-alt ml-1 pointer js-confirm" data-url="<?= $this->basePath('acl/delete/'.$acl->getId()) ?>" title="Jogosultság törlés"></i>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<button type="button" class="btn btn-primary js-modal-load" data-url="<?= $this->basePath('acl/new/'.$user->getId()) ?>" data-toggle="modal" data-target="#modal">Új jogosultság</button>
