<h4>Jogosultság létrehozása</h4>
<form method="post" action="<?= $this->basePath('acl/new/'.$user->getId()) ?>">
<div class="form-group row">
        <label class="col-sm-2 col-form-label" for="staticUser">Felhasználó</label>
        <div class="col-sm-6">
            <input type="text" readonly class="form-control-plaintext" id="staticUser" value="<?= $user->getFullName() ?>">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="category">Kategória</label>
        <div class="col-sm-6">
            <select class="form-control" name="category" id="category">
                <option value="0">-minden-</option>
                <?= $this->partial('block/category_option', ['categories' => $categories, 'parentName' => '']) ?>
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="exampleCheck2">Feltölthet</label>
        <div class="col-sm-6 ml-4">
            <input type="checkbox" name="canupload" class="form-check-input" id="exampleCheck2">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="exampleCheck3">Letölthet</label>
        <div class="col-sm-6 ml-4">
            <input type="checkbox" name="candownload" class="form-check-input" id="exampleCheck3">
        </div>
    </div>
</form>
