<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Ncatalog')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('vendor/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('vendor/css/fontawesome-all.min.css'))
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('js/core.js'))
            ->prependFile($this->basePath('vendor/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor/js/jquery.min.js'))
        ?>
    </head>
    <body>
        <?= $this->content ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
